# Generated by Django 3.1.2 on 2020-10-20 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CLSDimension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_height', models.IntegerField(blank=True, null=True)),
                ('list_width', models.IntegerField(blank=True, null=True)),
                ('detail_height', models.IntegerField(blank=True, null=True)),
                ('detail_width', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'CLS dimension',
                'verbose_name_plural': 'CLS dimensions',
            },
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to use title or name')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to use title or name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(blank=True, max_length=500)),
                ('is_traditional', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/')),
                ('image_timestamp', models.FloatField(default=0.0)),
                ('srcsets', models.JSONField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0, help_text='Higher number equals higher position. Leave 0 for default.')),
                ('cls_dimension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.clsdimension')),
                ('keywords', models.ManyToManyField(blank=True, to='art.Keyword')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ('-ordering', '-created_at'),
            },
        ),
    ]
