# Generated by Django 3.1.2 on 2020-10-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to use title or name')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Keyword',
                'verbose_name_plural': 'Keywords',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to use title or name')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50)),
                ('short_description', models.TextField(max_length=500)),
                ('is_traditional', models.BooleanField(default=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artwork/%Y/%m/')),
                ('image_timestamp', models.FloatField(default=0.0)),
                ('srcsets', models.JSONField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0, help_text='Higher number equals higher position. Leave 0 for default.')),
                ('cls_list_width', models.IntegerField(blank=True, null=True)),
                ('cls_list_height', models.IntegerField(blank=True, null=True)),
                ('cls_detail_width', models.IntegerField(blank=True, null=True)),
                ('cls_detail_height', models.IntegerField(blank=True, null=True)),
                ('keywords', models.ManyToManyField(blank=True, to='art.Keyword')),
            ],
            options={
                'verbose_name': 'Artwork',
                'verbose_name_plural': 'Artworks',
                'ordering': ('-ordering', '-created_at'),
            },
        ),
    ]
