# Generated by Django 3.1.2 on 2020-10-22 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave empty to use title or name', unique=True),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='title',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='slug',
            field=models.SlugField(blank=True, help_text='Leave empty to use title or name', unique=True),
        ),
    ]
