# Generated by Django 3.1.2 on 2020-10-29 16:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0002_artworkdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='artworkdetail',
            name='cls_dimension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.clsdimension'),
        ),
        migrations.AlterField(
            model_name='artworkdetail',
            name='image',
            field=models.ImageField(blank=True, help_text='Use a jpeg or png image (960x960 or larger).', null=True, upload_to='artwork/detail/%Y/%m/'),
        ),
    ]
