# Generated by Django 3.1.2 on 2020-10-31 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0004_auto_20201029_1910'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Higher number equals higher position. Leave 0 for default.'),
        ),
        migrations.AlterField(
            model_name='artworkdetail',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Higher number equals higher position. Leave 0 for default.'),
        ),
    ]
