# Generated by Django 3.1.2 on 2020-11-03 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0005_auto_20201031_0953'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtworkThumbnail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_published', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('image_timestamp', models.FloatField(default=0.0)),
                ('srcsets', models.JSONField(blank=True, null=True)),
                ('title', models.CharField(max_length=100, verbose_name='image title')),
                ('image', models.ImageField(blank=True, help_text='Use a jpeg or png image (960x960 or larger).', null=True, upload_to='artwork/thumbnail/%Y/%m/')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Higher number equals higher position. Leave 0 for default.')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='art.artwork')),
                ('cls_dimension', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.clsdimension')),
            ],
            options={
                'verbose_name': 'Artwork thumbnail',
                'verbose_name_plural': 'Artwork thumbnails',
                'ordering': ('-ordering', '-created_at'),
            },
        ),
        migrations.DeleteModel(
            name='ArtworkDetail',
        ),
    ]
