# Generated by Django 3.1.3 on 2020-11-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20201103_1104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='short_description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
