# Generated by Django 3.1.3 on 2020-11-08 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0007_auto_20201106_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='artworkthumbnail',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='keyword',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
