# Generated by Django 3.1.3 on 2020-11-09 22:19

from django.db import migrations, models
import spirsa.utils


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0008_auto_20201108_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=spirsa.utils.get_artwork_image_path),
        ),
        migrations.AlterField(
            model_name='artworkthumbnail',
            name='image',
            field=models.ImageField(blank=True, help_text='Use a jpeg or png image (960x960 or larger).', null=True, upload_to=spirsa.utils.get_artwork_thumbnail_path),
        ),
    ]
