# Generated by Django 3.2.13 on 2022-06-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0011_auto_20220314_1854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artwork',
            old_name='is_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='artworkthumbnail',
            old_name='is_published',
            new_name='published',
        ),
        migrations.RenameField(
            model_name='keyword',
            old_name='is_published',
            new_name='published',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_featured',
        ),
        migrations.RemoveField(
            model_name='artwork',
            name='is_traditional',
        ),
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, help_text='Leave empty to use title or name', unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=50, unique=True)),
                ('artworks', models.ManyToManyField(blank=True, to='art.Artwork')),
            ],
            options={
                'verbose_name': 'Collection',
                'verbose_name_plural': 'Collections',
                'ordering': ('-created_at',),
            },
        ),
    ]
