# Generated by Django 4.0.6 on 2024-06-23 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0013_alter_collection_options_collection_ordering_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ('-ordering', '-created_at'), 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('-ordering', 'show_in_navigation'), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='Descending (largest to smallest)'),
        ),
        migrations.AlterField(
            model_name='collection',
            name='ordering',
            field=models.PositiveIntegerField(default=1, help_text='Descending (largest to smallest)'),
        ),
    ]
