# Generated by Django 6.0.2 on 2026-03-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0014_alter_artwork_options_alter_collection_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ('ordering',), 'verbose_name': 'Artwork', 'verbose_name_plural': 'Artworks'},
        ),
        migrations.AlterModelOptions(
            name='artworkthumbnail',
            options={'ordering': ('ordering',), 'verbose_name': 'Artwork thumbnail', 'verbose_name_plural': 'Artwork thumbnails'},
        ),
        migrations.AlterModelOptions(
            name='collection',
            options={'ordering': ('ordering',), 'verbose_name': 'Collection', 'verbose_name_plural': 'Collections'},
        ),
        migrations.AlterField(
            model_name='artwork',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='artworkthumbnail',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='collection',
            name='ordering',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
