# Generated by Django 6.0.2 on 2026-03-15 16:45

from django.db import migrations
from django.db.models import Max


def invert_ordering(apps, schema_editor):
    """Invert ordering values so existing descending order is preserved as ascending."""
    for model_name in ("Artwork", "ArtworkThumbnail", "Collection"):
        Model = apps.get_model("art", model_name)
        max_val = Model.objects.aggregate(m=Max("ordering"))["m"]
        if max_val is None:
            continue
        for obj in Model.objects.all():
            obj.ordering = max_val - obj.ordering
            obj.save(update_fields=["ordering"])


def reverse_invert(apps, schema_editor):
    invert_ordering(apps, schema_editor)


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0015_sortable_ordering"),
    ]

    operations = [
        migrations.RunPython(invert_ordering, reverse_invert),
    ]
