# Generated by Django 6.0.2 on 2026-04-13 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("art", "0016_invert_ordering_values"),
    ]

    operations = [
        migrations.CreateModel(
            name="Label",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("slug", models.SlugField(blank=True, help_text="Leave empty to use title or name", unique=True)),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name": "Label",
                "verbose_name_plural": "Labels",
                "ordering": ("name",),
            },
        ),
        migrations.AddField(
            model_name="artworkthumbnail",
            name="label",
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name="thumbnails", to="art.label"),
        ),
    ]
