CACHE_SECONDS = 600
HOME_URL_NAME = 'digital'

DEFAULT_QUALITY = 80
DEFAULT_TYPE = 'jpeg'
LARGE = 'large'
MEDIUM = 'medium'
SMALL = 'small'
SMALL_WIDTH = 380
MEDIUM_WIDTH = SMALL_WIDTH * 2
LARGE_WIDTH = SMALL_WIDTH * 3
DEFAULT_WIDTH = MEDIUM_WIDTH
PROFILE_WIDTH = 350
RATIO_THRESHOLD = 1.2
BASE_HEIGHT = 400

SRCSET_TYPES = ('webp', DEFAULT_TYPE, )
SRCSET_MAPPING = {srcset: [] for srcset in [
    '{}_{}'.format(t, s) for t in SRCSET_TYPES for s in (LARGE, MEDIUM, SMALL, )]
}
PROFILE_VARIATION_SETS = (
    (SMALL, PROFILE_WIDTH, PROFILE_WIDTH * 2),
    (SMALL, PROFILE_WIDTH, PROFILE_WIDTH),
)
LANDSCAPE_VARIATION_SETS = (
    (LARGE, LARGE_WIDTH, LARGE_WIDTH * 2),
    (LARGE, LARGE_WIDTH, LARGE_WIDTH),
    (MEDIUM, MEDIUM_WIDTH, MEDIUM_WIDTH * 2),
    (MEDIUM, MEDIUM_WIDTH, MEDIUM_WIDTH),
    (SMALL, SMALL_WIDTH, SMALL_WIDTH * 2),
    (SMALL, SMALL_WIDTH, SMALL_WIDTH),
)
VARIATION_SETS = (
    (MEDIUM, MEDIUM_WIDTH, MEDIUM_WIDTH * 2),
    (MEDIUM, MEDIUM_WIDTH, MEDIUM_WIDTH),
    (SMALL, SMALL_WIDTH, SMALL_WIDTH * 2),
    (SMALL, SMALL_WIDTH, SMALL_WIDTH),
)

FB_SHARE_URL = 'https://www.facebook.com/sharer.php?u='
TT_SHARE_URL = 'https://twitter.com/intent/tweet?url='
IN_SHARE_URL = 'https://www.linkedin.com/sharing/share-offsite/?url='
PT_SHARE_URL = 'https://pinterest.com/pin/create/button/?url='
