# Generated by Django 3.1.1 on 2020-10-17 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MetaInformation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('meta_title', models.CharField(max_length=100)),
                ('meta_description', models.TextField(max_length=500)),
                ('meta_keywords', models.TextField(help_text='Separate each keyword group with a comma.', max_length=200)),
                ('meta_image', models.ImageField(blank=True, null=True, upload_to='%Y/%m/')),
                ('meta_image_title', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Meta information',
                'verbose_name_plural': 'Meta information',
            },
        ),
    ]
