# Generated by Django 3.1.2 on 2020-10-27 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spirsa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abountcontactinformation',
            name='image',
            field=models.ImageField(blank=True, help_text='Use a jpeg or png image (800x800 or larger).', null=True, upload_to='spirsa/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='abountcontactinformation',
            name='image_title',
            field=models.CharField(blank=True, default='', max_length=100),
            preserve_default=False,
        ),
    ]
