# Generated by Django 3.1.2 on 2020-10-29 18:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0003_auto_20201029_1748'),
        ('spirsa', '0002_auto_20201027_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abountcontactinformation',
            name='image_title',
        ),
        migrations.AddField(
            model_name='abountcontactinformation',
            name='cls_dimension',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='art.clsdimension'),
        ),
        migrations.AddField(
            model_name='abountcontactinformation',
            name='title',
            field=models.CharField(blank=True, max_length=100, verbose_name='image title'),
        ),
        migrations.AlterField(
            model_name='abountcontactinformation',
            name='image',
            field=models.ImageField(blank=True, help_text='Use a jpeg or png image (760x760 or larger).', null=True, upload_to='spirsa/%Y/%m/'),
        ),
    ]
