# Generated by Django 3.1.2 on 2020-11-03 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('art', '0006_auto_20201103_1104'),
        ('spirsa', '0003_auto_20201029_1904'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AbountContactInformation',
            new_name='AboutContactInformation',
        ),
    ]
